version: "3.8"

services:

  house_finder_vpn:
    container_name: house_finder_vpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    environment:
      - KILL_SWITCH=true
    image: yacht7/openvpn-client
    network_mode: bridge
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    volumes:
      - ./openvpn:/data/vpn

  house_finder:
    command: /bin/sh -c "pip install -r requirements.txt && python -u main.py"
    container_name: house_finder
    depends_on:
      - house_finder_vpn
    image: python:3.9.0-alpine
    working_dir: /app
    network_mode: service:house_finder_vpn
    restart: unless-stopped
    volumes: 
      - ./:/app
